# Generated by Django 6.0.5 on 2026-05-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProduto', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricaoProduto', models.TextField(verbose_name='Descrição')),
                ('precoProduto', models.FloatField(verbose_name='Preço')),
                ('tamanhoProduto', models.TextField(choices=[('2p', 'PP'), ('p', 'P'), ('m', 'M'), ('g', 'G'), ('2g', 'GG')], verbose_name='Tamanho')),
                ('corProduto', models.TextField(verbose_name='Cor')),
                ('estoqueProduto', models.PositiveIntegerField(default=0, verbose_name='Estoque')),
            ],
        ),
    ]
