# Generated by Django 6.0.5 on 2026-05-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProduto', models.CharField(max_length=200)),
                ('descricaoProduto', models.TextField()),
                ('precoProduto', models.FloatField()),
                ('tamanhoProduto', models.TextField(choices=[('PP', 'Minusculo'), ('P', 'Pequeno'), ('M', 'Mediano'), ('G', 'Grande'), ('GG', 'Imenso')], default='M')),
                ('corProduto', models.TextField()),
            ],
        ),
    ]
