# Generated by Django 6.0.5 on 2026-06-02 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProduto', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricaoProduto', models.TextField(verbose_name='Descrição')),
                ('precoProduto', models.DecimalField(decimal_places=2, default=0, max_digits=999999, verbose_name='Preço')),
            ],
        ),
        migrations.CreateModel(
            name='VariacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanhoProduto', models.TextField(choices=[('p', 'P'), ('m', 'M'), ('g', 'G')], default='m', verbose_name='Tamanho')),
                ('corProduto', models.TextField(verbose_name='Cor')),
                ('estoqueProduto', models.PositiveIntegerField(default=0, verbose_name='Estoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produtos.produtos', verbose_name='Produto')),
            ],
        ),
    ]
