# Generated by Django 6.0.5 on 2026-06-04 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carrinho', '0002_initial'),
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtos',
            new_name='Produto',
        ),
    ]
