# Generated by Django 6.0.5 on 2026-06-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricaoProduto',
            field=models.TextField(max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='variacaoproduto',
            name='corProduto',
            field=models.CharField(verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='variacaoproduto',
            name='tamanhoProduto',
            field=models.CharField(choices=[('p', 'P'), ('m', 'M'), ('g', 'G')], default='m', verbose_name='Tamanho'),
        ),
    ]
