# Generated by Django 6.0.5 on 2026-06-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variacaoproduto',
            name='atividadeProduto',
        ),
        migrations.AddField(
            model_name='produto',
            name='ativoProduto',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
