# Generated by Django 6.0.5 on 2026-05-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='tamanhoProduto',
            field=models.TextField(choices=[('2p', 'PP'), ('p', 'P'), ('m', 'M'), ('g', 'G'), ('2g', 'GG')]),
        ),
    ]
