# Generated by Django 6.0.5 on 2026-05-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0002_alter_produtos_tamanhoproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='estoqueProduto',
            field=models.PositiveIntegerField(default=0, verbose_name='Estoque'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='corProduto',
            field=models.TextField(verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='descricaoProduto',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='nomeProduto',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='precoProduto',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='tamanhoProduto',
            field=models.TextField(choices=[('2p', 'PP'), ('p', 'P'), ('m', 'M'), ('g', 'G'), ('2g', 'GG')], verbose_name='Tamanho'),
        ),
    ]
