# Generated by Django 6.0.5 on 2026-06-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado'), ('C', 'Cancelado')], default='A', max_length=1, verbose_name='Estado')),
                ('carrinhoData', models.DateField(auto_now_add=True, verbose_name='Abertura')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
            ],
        ),
    ]
