# Generated by Django 6.0.5 on 2026-05-24 21:14

import Produtos.models
import django.db.models.fields.related
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(verbose_name=Produtos.models.Produtos)),
                ('estado', models.TextField(choices=[('A', 'Aberto'), ('F', 'Fechado'), ('C', 'Cancelado')], default='A')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.fields.related.OneToOneField, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
