# Generated by Django 6.0.5 on 2026-05-24 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrinho', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='item',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='carrinhoData',
            field=models.DateField(auto_now_add=True, default='2026-05-24'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='estado',
            field=models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado'), ('C', 'Cancelado')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
