# Generated by Django 6.0.5 on 2026-06-02 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Carrinho', '0001_initial'),
        ('Produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dono'),
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='carrinho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carrinho.carrinho', verbose_name='Carrinho'),
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produtos.produtos', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='variacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produtos.variacaoproduto', verbose_name='Variação'),
        ),
    ]
