# Generated by Django 6.0.5 on 2026-05-24 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrinho', '0002_remove_carrinho_item_carrinho_carrinhodata_and_more'),
        ('Produtos', '0002_alter_produtos_tamanhoproduto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='carrinhoData',
            field=models.DateField(auto_now_add=True, verbose_name='InicioCarrinho'),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='estado',
            field=models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado'), ('C', 'Cancelado')], default='A', max_length=1, verbose_name='EstadoCarrinho'),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='UsuárioCarrinho'),
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='QuantidadeItemCarrinho')),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carrinho.carrinho', verbose_name='ItemCarrinho')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produtos.produtos', verbose_name='ProdutoItemCarrinho')),
            ],
        ),
    ]
