# Generated by Django 6.0.5 on 2026-06-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrinho', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='pagamentoPedido',
            field=models.TextField(choices=[('picx', 'Pix'), ('cred', 'Crédito'), ('debt', 'Débito')], default='', verbose_name='Forma de pagamento'),
            preserve_default=False,
        ),
    ]
