# Generated by Django 6.0.5 on 2026-05-24 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrinho', '0003_alter_carrinho_carrinhodata_alter_carrinho_estado_and_more'),
        ('Produtos', '0003_produtos_estoqueproduto_alter_produtos_corproduto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrinho',
            name='carrinho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carrinho.carrinho', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='itemcarrinho',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produtos.produtos', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='itemcarrinho',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
