# Generated by Django 6.0.5 on 2026-05-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastrar_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.TextField(max_length=50)),
                ('telefone', models.TextField(max_length=14)),
                ('cep', models.TextField(max_length=10)),
                ('endereco', models.TextField()),
            ],
        ),
    ]
