# Generated by Django 6.0.5 on 2026-06-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapadrao',
            name='cep',
            field=models.TextField(max_length=9),
        ),
        migrations.AlterField(
            model_name='contapadrao',
            name='telefone',
            field=models.TextField(max_length=13),
        ),
    ]
