# Generated by Django 6.0.5 on 2026-05-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastrar_produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=200)),
                ('preco_produto', models.FloatField()),
                ('tamanho_produto', models.TextField()),
                ('cor_produto', models.TextField()),
                ('descricao_produto', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cadastrar_user',
            name='role',
            field=models.TextField(choices=[('L', 'Lojista'), ('C', 'Cliente')], default='C'),
        ),
    ]
