# Generated by Django 6.0.5 on 2026-06-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapadrao',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
