# Generated by Django 6.0.5 on 2026-05-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contapadrao',
            name='senha',
        ),
        migrations.AlterField(
            model_name='contapadrao',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
