# Generated by Django 6.0.5 on 2026-06-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0002_alter_contapadrao_cep_alter_contapadrao_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contapadrao',
            name='groups',
        ),
        migrations.AddField(
            model_name='contapadrao',
            name='groups',
            field=models.TextField(choices=[('L', 'Lojista'), ('C', 'Cliente')], default='C'),
        ),
    ]
