# Generated by Django 6.0.5 on 2026-06-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0003_remove_contapadrao_groups_contapadrao_groups'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapadrao',
            name='endereco',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='contapadrao',
            name='groups',
        ),
        migrations.AddField(
            model_name='contapadrao',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
    ]
