# Generated by Django 6.0.5 on 2026-06-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContatarSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeSuporte', models.TextField(max_length=99, verbose_name='Nome completo')),
                ('emailSuporte', models.EmailField(max_length=254, verbose_name='Seu melhor e-mail')),
                ('assuntoSuporte', models.TextField(max_length=99, verbose_name='Assunto')),
                ('mensagemSuporte', models.TextField(max_length=600, verbose_name='Descreva seu problema')),
            ],
        ),
    ]
