# Generated by Django 6.0.5 on 2026-06-15 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Carrinho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPedido', models.DateField(auto_now_add=True, verbose_name='Data de abertura')),
                ('statusPedido', models.TextField(choices=[('Pend', 'Pendente'), ('Apro', 'Aprovado'), ('Canc', 'Cancelado')], verbose_name='Status')),
                ('pagamentoPedido', models.TextField(choices=[('picx', 'Pix'), ('cred', 'Crédito'), ('debt', 'Débito')], verbose_name='Forma de pagamento')),
                ('itensPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carrinho.itemcarrinho', verbose_name='Itens')),
            ],
        ),
    ]
