# Generated by Django 6.0.5 on 2026-06-15 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidomodel',
            name='pagamentoPedido',
        ),
    ]
